import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nested Route",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>This is the nav defined in nested layout.tsx</nav>
        {children}
        <footer>This is the footer defined in nested layout.tsx</footer>
      </body>
    </html>
  );
}
